-- LODGE_DETAILS TABLE

CREATE TABLE LODGE_DETAILS
(
    LODGE_NAME      VARCHAR2(30) PRIMARY KEY,
    LODGE_MANAGER   VARCHAR2(30) NOT NULL,
    LODGE_ADDRESS   VARCHAR2(30)
);

-- EMP_DETAILS TABLE

CREATE TABLE EMP_DETAILS
(
    EMPNO        NUMBER PRIMARY KEY,
    FIRST_NAME   VARCHAR2(30) NOT NULL,
    LAST_NAME    VARCHAR2(30) NOT NULL,
    LODGE_NAME   VARCHAR2(30),

    CONSTRAINT FK_EMP_LODGE
    FOREIGN KEY (LODGE_NAME)
    REFERENCES LODGE_DETAILS(LODGE_NAME)
);

-- SKILL_DETAILS TABLE

CREATE TABLE SKILL_DETAILS
(
    SKILL        VARCHAR2(30) PRIMARY KEY,
    SKILL_DESC   VARCHAR2(30)
);

-- EMP_SKILL TABLE

CREATE TABLE EMP_SKILL
(
    EMPNO   NUMBER,
    SKILL   VARCHAR2(30),
    GRADE   NUMBER(10),

    CONSTRAINT PK_EMP_SKILL
    PRIMARY KEY (EMPNO,SKILL),

    CONSTRAINT FK_EMP
    FOREIGN KEY (EMPNO)
    REFERENCES EMP_DETAILS(EMPNO),

    CONSTRAINT FK_SKILL
    FOREIGN KEY (SKILL)
    REFERENCES SKILL_DETAILS(SKILL)
);

INSERT INTO EMP_DETAILS VALUES
(101,'James','Jackson','Rajesh Lodge');

INSERT INTO EMP_DETAILS VALUES
(102,'Kalpash','Raj','Gooday Lodge');

INSERT INTO EMP_DETAILS VALUES
(103,'Jasmine','Joy','Jessy Lodge');

INSERT INTO SKILL_DETAILS VALUES
('Oracle SQL','Oracle Corporation');

INSERT INTO SKILL_DETAILS VALUES
('Dot Net','Microsoft');

INSERT INTO SKILL_DETAILS VALUES
('Sybase','SAP Corporation');
INSERT INTO EMP_SKILL VALUES
(101,'Oracle SQL',9);

INSERT INTO EMP_SKILL VALUES
(101,'Sybase',8);

INSERT INTO EMP_SKILL VALUES
(102,'Dot Net',9);

INSERT INTO EMP_SKILL VALUES
(103,'Oracle SQL',8);

COMMIT;
UPDATE EMP_DETAILS
SET LODGE_NAME='Gooday Lodge'
WHERE EMPNO=101;

COMMIT;
DELETE FROM EMP_SKILL
WHERE EMPNO=103;

DELETE FROM EMP_DETAILS
WHERE EMPNO=103;

COMMIT;
SELECT E.EMPNO,
       E.FIRST_NAME,
       ES.SKILL
FROM EMP_DETAILS E
JOIN EMP_SKILL ES
ON E.EMPNO=ES.EMPNO
WHERE UPPER(ES.SKILL)=UPPER('&SKILL');
SELECT E.FIRST_NAME,
       ES.SKILL,
       L.LODGE_MANAGER
FROM EMP_DETAILS E
JOIN EMP_SKILL ES
ON E.EMPNO=ES.EMPNO
JOIN LODGE_DETAILS L
ON E.LODGE_NAME=L.LODGE_NAME;
SELECT COUNT(*) AS TOTAL_SKILLS
FROM EMP_SKILL
WHERE EMPNO=101;
SELECT E.FIRST_NAME
FROM EMP_DETAILS E
JOIN EMP_SKILL ES
ON E.EMPNO=ES.EMPNO
WHERE ES.SKILL='Oracle SQL';
CREATE VIEW EMP_VIEW AS

SELECT
E.EMPNO,
E.FIRST_NAME,
ES.SKILL,
L.LODGE_MANAGER

FROM EMP_DETAILS E

JOIN EMP_SKILL ES
ON E.EMPNO=ES.EMPNO

JOIN LODGE_DETAILS L
ON E.LODGE_NAME=L.LODGE_NAME;
CREATE SYNONYM EMPV
FOR EMP_VIEW;
CREATE INDEX IDX_SKILL
ON EMP_SKILL(SKILL);