CREATE TABLE EMPTEST AS
SELECT * FROM EMP;

INSERT INTO EMPTEST (EMPNO, ENAME, SAL)
VALUES (9999, USER, 5000);

UPDATE EMPTEST
SET SAL = SAL * 1.15
WHERE ENAME = 'TURNER';

COMMIT;

UPDATE EMPTEST
SET SAL = (
    SELECT SAL
    FROM EMPTEST
    WHERE ENAME = 'SCOTT'
)
WHERE ENAME = 'SMITH';

UPDATE EMPTEST
SET SAL = SAL * 1.10
WHERE DEPTNO = (
    SELECT DEPTNO
    FROM DEPT
    WHERE LOC = 'NEW YORK'
);

UPDATE EMPTEST
SET COMM = NULL;

DELETE FROM EMPTEST
WHERE DEPTNO = (
    SELECT DEPTNO
    FROM DEPT
    WHERE DNAME = 'SALES'
);

DELETE FROM EMPTEST
WHERE DEPTNO = (
    SELECT DEPTNO
    FROM EMPTEST
    WHERE ENAME = UPPER('&ENAME')
)
AND ENAME <> UPPER('&ENAME');

CREATE TABLE EMP2 AS
SELECT EMPNO, ENAME, SAL
FROM EMP
WHERE 1 = 2;

CREATE TABLE EMP3 AS
SELECT EMPNO, JOB
FROM EMP
WHERE 1 = 2;

INSERT ALL
INTO EMP2 (EMPNO, ENAME, SAL)
VALUES (EMPNO, ENAME, SAL)
INTO EMP3 (EMPNO, JOB)
VALUES (EMPNO, JOB)
SELECT * FROM EMP;

TRUNCATE TABLE EMP2;

INSERT INTO EMP2 VALUES (7788, 'SMITH', 4500);

INSERT INTO EMP2 VALUES (7654, 'JACK', 3500);

COMMIT;

MERGE INTO EMP2 E2
USING EMP E
ON (E2.EMPNO = E.EMPNO)
WHEN MATCHED THEN
UPDATE SET
E2.ENAME = E.ENAME,
E2.SAL = E.SAL
WHEN NOT MATCHED THEN
INSERT (EMPNO, ENAME, SAL)
VALUES (E.EMPNO, E.ENAME, E.SAL);

SELECT * FROM EMP2;

ROLLBACK;

MERGE INTO EMP2 E2
USING (
    SELECT *
    FROM EMP
    WHERE EMPNO = 7788
       OR SAL > 3000
) E
ON (E2.EMPNO = E.EMPNO)
WHEN MATCHED THEN
UPDATE SET
E2.ENAME = E.ENAME,
E2.SAL = E.SAL
WHERE E.EMPNO = 7788
WHEN NOT MATCHED THEN
INSERT (EMPNO, ENAME, SAL)
VALUES (E.EMPNO, E.ENAME, E.SAL)
WHERE E.SAL > 3000;

SELECT * FROM EMP2;

CREATE USER C##WIPRO IDENTIFIED BY wipro;

GRANT CONNECT, RESOURCE TO C##WIPRO;

GRANT ALL ON EMP TO C##WIPRO;

DELETE FROM EMP
WHERE DEPTNO = 10;

CONNECT C##WIPRO/wipro;

DELETE FROM SCOTT.EMP
WHERE DEPTNO = 10;

CONNECT SYSTEM;

ROLLBACK;

CONNECT C##WIPRO/wipro;

SELECT *
FROM SCOTT.EMP
FOR UPDATE WAIT 20;

ROLLBACK;

CONNECT SYSTEM;

SELECT * FROM EMP;

ROLLBACK;

CONNECT C##WIPRO/wipro;

ROLLBACK;