CREATE TABLE DEPARTMENTS (
    DEPT_ID NUMBER PRIMARY KEY,
    DEPT_NAME VARCHAR2(30)
);

CREATE TABLE EMPLOYEES (
    EMP_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(30),
    LAST_NAME VARCHAR2(30),
    JOB_ID VARCHAR2(20),
    SALARY NUMBER,
    MANAGER_ID NUMBER,
    DEPT_ID NUMBER
);

CREATE TABLE LOCATIONS (
    LOCATION_ID NUMBER PRIMARY KEY,
    CITY VARCHAR2(30)
);
